vich_uploader:
    db_driver: orm

    mappings:
        recipes_images:
            uri_prefix: '%recipes_images%'
            upload_destination: '%kernel.project_dir%/public%recipes_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
